name: Checkmarx One Scan

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      # Other steps...
      
      - name: Install JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
      
      - name: Verify JFrog CLI Installation
        run: jfrog -v

      - name: Configure JFrog CLI
        run: |
          export JF_ARTIFACTORY_URL="${{ secrets.JF_URL }}"
          export JF_ARTIFACTORY_ACCESS_TOKEN="${{ secrets.JF_ACCESS_TOKEN }}"

      - name: Push Docker image to Artifactory
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        run: |
          jfrog rt docker-push yalina/yalina:myapp devnet-ya--virtual-version1/yalina:myapp --url="$JF_URL" --access-token="$JF_ACCESS_TOKEN"
          
